language:
  - go
go:
  - "1.11.x"
before_script:
  - go get -v github.com/gin-gonic/gin
script:
  - go build application.go
  - go test ./... -cover -v
  - docker build -t template_go .
  - docker run -d -p 8080:8080 --name template_go_container template_go
  - curl http://127.0.0.1:8080/v1/hello_world/1
  - docker stop template_go_container
  - docker rm template_go_container
  - docker rmi template_go

